services:
  web:
    build:
      context: ./dockerfiles
      dockerfile: php.Dockerfile
    ports:
      - "911:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    volumes:
      - db_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8180:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpass
    depends_on:
      - db
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.Dockerfile
    volumes:
      - .:/var/www/html

volumes:
  db_data: 